networks:
    web-app-project-skeleton:
services:
    web: 
        image: ${NGINX_IMAGE}
        ports:
            - "8080:80"
        volumes:
            - ./backend:/var/www/project
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - worker
        networks:
            - web-app-project-skeleton
    app:
        image: ${APP_IMAGE}
        ports:
            - "9000:9000"
        volumes:
            - ./backend:/var/www/project
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_ENV: ${APP_ENV}
            APP_VERSION: ${APP_VERSION}
            MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
            DATABASE_URL: "mysql://root:secret@db:3306/app?serverVersion=8.0.31&charset=utf8mb4"
            REDIS_URL: "redis://shared-cache:6379"
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        networks:
            - web-app-project-skeleton
    worker:
        image: ${APP_IMAGE}
        volumes:
            - ./backend:/var/www/project
        command: ["bin/console", "messenger:consume", "async"]
        depends_on:
            db:
                condition: service_healthy
        environment:
            APP_ENV: ${APP_ENV}
            APP_VERSION: ${APP_VERSION}
            MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
            DATABASE_URL: "mysql://root:secret@db:3306/app?serverVersion=8.0.31&charset=utf8mb4"
            REDIS_URL: "redis://shared-cache:6379"
        networks:
            - web-app-project-skeleton
    db:
        image: ${MYSQL_IMAGE}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55
        networks:
            - web-app-project-skeleton
    db-admin:
        image: ${ADMINER_IMAGE}
        environment:
            ADMINER_DEFAULT_SERVER: db
        ports:
            - "8085:8080"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - web-app-project-skeleton
    dashboard:
        image: b4bz/homer:latest
        volumes:
            - ./dashboard/assets:/www/assets
            - ./backend/report:/www/public/report
            - ./backend/coverage:/www/public/coverage
        ports:
            - "8000:8080"
        user: "1000:1001"
        restart: unless-stopped
        networks:
            - web-app-project-skeleton
volumes:
    mysql_data: {}
